workspace:
  base: /go
  path: src/github.com/kerkerj/simple-go-server-test

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  build:
    image: alpine:3.7
    commands:
      - echo "build"
  test:
    image: golang:${GO_VERSION}-alpine
    commands:
      - echo "run tests"
      - go install
      - go test -v ./...

matrix:
  GO_VERSION:
    - "1.9"
    - "1.10"
